### ISSUE TITLE
Progress tracking for v2.0

### ISSUE THREAD

**Issue by HackerDaGreat57** [HackerDaGreat57/3D-License-Suite#5]
The README should contain short but also detailed information about these licenses, why they exist, etc.

- [ ] Software license - 3dSL
  - [ ] Write the general gist of the license
  - [ ] Explain why this license exists (get some dirt on Adobe while you're at it)
  - [ ] Write the license itself (there is already some progress on this)
- [ ] Video/audio license - 3dVAL
  - [ ] Write the general gist of the license
  - [ ] Explain why this license exists (mainly to let people create memes/remixes)
  - [ ] Write the license itself (basically a paraphrase of the software license)
- [ ] Text license - 3dTL
  - [ ] Write the general gist of the license
  - [ ] Explain why this license exists (mainly for banning paywalls and letting information flow more freely)
  - [ ] Write the license itself
- [ ] Picture license - 3dPL
  - [ ] Write the general gist of the license
  - [ ] Explain why this license exists (mainly for making royalty-free the standard and letting people use each other's art/creations without having to ask)
  - [ ] Write the license itself

The to-do list may be changed, we'll see...
